version: "3.9"
services:
  server:
    container_name: server
    build: ./index
    restart: always
    privileged: true
    ports:
      - 80:80
    volumes:
      - ./data/nginx:/etc/nginx/conf.d

  web-api:
    container_name: web-api
    build: ./webapi
    restart: always
    privileged: true
    ports:
      - 5173:5173
    environment:
      - ASPNETCORE_URLS=http://+:5173

  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.12
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'

  scanner:
    container_name: scanner
    build: ./scanner
    restart: always
    privileged: true
    ports:
      - 3000:3000

volumes:
  rabbitmq_data:
    driver: local