version: "3.9"
services:
  server:
    container_name: server
    build: ./index
    restart: always
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./certbot/www/:/var/www/certbot/:ro
    networks:
          - web_net
    depends_on:
      - web-api

  web-api:
    container_name: web-api
    build: ./webapi
    restart: always
    privileged: true
    ports:
      - 5173:5173
    environment:
      - ASPNETCORE_URLS=http://+:5173
      - QUEUE_ENABLED=TRUE
      - QUEUE_HOST=queue
    networks:
          - web_net
    depends_on:
      - queue

  queue:
    container_name: queue
    image: docker.io/bitnami/rabbitmq:3.12
    restart: always
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
    networks:
          - web_net
 
networks:
    web_net:
      external: false
      driver:  bridge

volumes:
  rabbitmq_data:
    driver: local