version: "3.9"
services:
  server:
    container_name: server
    build: ./index
    restart: always
    privileged: true
    ports:
      - 80:80
    volumes:
      - ./data/nginx:/etc/nginx/conf.d

  web-api:
    container_name: web-api
    build: ./webapi
    restart: always
    privileged: true
    ports:
      - 5173:5173
    environment:
      - ASPNETCORE_URLS=http://+:5173