version: "3.9"
services:
    web-api-0:
      image: scanner
      build: ./webapi
      restart: always
      privileged: true
      environment:
        - QUEUE_ENABLED=TRUE
        # - HTTP_PROXY=http://mozb7w2y:mozb7w2y@103.122.140.122:39997
        # - HTTPS_PROXY=http://mozb7w2y:mozb7w2y@103.122.140.122:39997
    
    # web-api-2:
    #   image: scanner
    #   restart: always
    #   privileged: true
    #   environment:
    #     - QUEUE_ENABLED=TRUE 

    # web-api-3:
    #   image: scanner
    #   build: ./webapi
    #   restart: always
    #   privileged: true
    #   environment:
    #     - QUEUE_ENABLED=TRUE 
    
    # web-api-4:
    #   image: scanner
    #   build: ./webapi
    #   restart: always
    #   privileged: true


    # web-api-5:
    #   image: scanner
    #   build: ./webapi
    #   restart: always
    #   privileged: true
